[package]
edition = "2021"
name    = "cpcodec"
version = "0.0.0"

[lib]
crate-type = ["staticlib"]
name       = "cpcodec"

[dependencies]
half = { version = "2.0.0", features = ["std"] }
libc = "0.2.132"
pco  = { version = "0.4.0", path = "../pco" }
